import React from "react";

const ProjectsText = () => {
  return (
    <div className="flex flex-col items-center mt-[50px] p-2 mb-10">
      <h2 className="text-6xl text-cyan-300 mb-10">Projects</h2>
      <p className="text-lg text-center text-white">
        I'm a passionate full-stack developer just starting out, and I recently
        built an AI-powered quiz app using the MERN stack. Users can register,
        pick subjects, take quizzes generated by AI, and even review past
        results. I focused on making it responsive, clean, and user-friendly
        with features like dark/light mode. It helped me grow a lot in React,
        Node.js, Zustand, and UI frameworks like Tailwind CSS and Chakra UI.
      </p>
    </div>
  );
};

export default ProjectsText;
